### ISSUE TITLE
Is it possible to use multiple audio devices?

### ISSUE THREAD

**Issue by EsteveSegura** [Flowr-es/node-microphone#14]
I am trying to detect the sound of multiple audio inputs ... Is this possible?

**Comment by Flowr-es** [comment]
You should be able to open for each audio input an stream. However I have not tested it... 

I would do something like this:
`
const Mic = require('node-microphone');
const SoundDetector = require('fromSomewhere');
[ 'audioDevice1', 'audioDevice2' ].forEach( device => {
let mic = new Mic( { device });
let micStream = mic.startRecording();
let soundDetector = new SoundDetector();
micStream.pipe( soundDetector );
});
`
