### ISSUE TITLE
Silence Detection: how would you go about it?

### ISSUE THREAD

**Issue by julien-c** [Flowr-es/node-microphone#4]
Any ideas?

**Comment by Flowr-es** [comment]
Two Options:
1. Do it yourself: Calculate from the pcm data the decibel or something else that indicates that there is silence. <--- If you do this, I would be interested in your solution

2. Use an existing library, e.g. pocketsphinx, snowboy or maybe alsa/pulseaudio/sox, they can probably provide you a silence detection. Also you could take a look to this module, it brings some silence detection with it: https://www.npmjs.com/package/mic

**Comment by Flowr-es** [comment]
I will close this one, it won't be part of this module.
