### ISSUE TITLE
node index.js ?

### ISSUE THREAD

**Issue by mimoraes** [Flowr-es/node-microphone#6]
How can I test my MIC ? nothing happens with 
pi@Rose:~/node/node_modules/node-microphone $ node index.js

**Comment by Flowr-es** [comment]
Hi,

node index.js will do nothing as it has to be required in your code and started.
Take a look to the simple example: https://github.com/MexXxo/node-microphone#simple-example
Just copy this snippet paste it, into your code and run it, than it should record some seconds.

But you have to exchange myWritableStream with an actual writable stream e.g.  https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options
